// Generated by `npm run auth:schema` (better-auth CLI). Do not hand-edit —
// re-run the script after changing the better-auth config in src/lib/auth.ts.
// This is a placeholder until that command has been run against a real
// DATABASE_URL.
export {}
